services:
  gpodder:
    image: ghcr.io/techwithjake/micro-gpodder-server:main
    container_name: micro-gpodder-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Phoenix
    volumes:
      - /path/to/folder:/var/www/server/data
    hostname: gpodder.localhost
    networks:
      - gpodder
    ports:
      - "8080:8080"